import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :bughouse, BughouseWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is handled by Fly.io's proxy (force_https = true in fly.toml).
# Do NOT set force_ssl here — it breaks Fly's internal health checks
# which hit the app directly on port 4000 without x-forwarded-proto.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
